---
- name: This sets up an httpd webserver
  hosts: web 
#  vars_files:
#    - "vars.yaml"
  vars_prompt:
    - name: "myname"
      private: no
      prompt: "What is your name?"

  vars:
    myname: "sudhakar-playbook"
    mycomp: "hp-playbook"

  tasks:
  - name: Install the httpd apps
    yum: name=httpd
  - name: start the httpd service
    service: name=httpd state=started
  - debug:
      msg: System {{ myname }} has uuid {{ ansible_product_uuid }}
  - debug: msg="System {{ myname }} has uuid {{ ansible_product_uuid }}"
  - debug: msg={{ ansible_product_uuid }}
  - debug: var=ansible_product_uuid
  - debug:
      var: ansible_product_uuid
  - debug:
      var: ansible_product_uuid

