---
- name: Start http service on multiple machine
  hosts: localhost
  tasks:
    - name: Ansible register variable basic.
      shell: "find *.txt" 
      args:
        chdir: group_vars 
#      args: 
#        state: started
      register: find_output
    - debug:
        msg: Files found in {{ find_output }}
...
